cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: estuate-img-s3-storage1

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: image-uploader

server:
  port: 8081
